Controllers/PagesController.cs
using Contentful.Core;
using Contentful.Core.Configuration;
using Contentful.Core.Models;
using Contentful.Core.Search;
using Contentful.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Contentful.Controllers
{
    public class PagesController : Controller
    {
        // GET: Pages
        //public async Task<ActionResult> Index(string PageID)
        //{
        //    HttpClient httpClient = new HttpClient();
        //    var options = new ContentfulOptions
        //    {
        //        DeliveryApiKey = "4df4c5c7ed276605d36b9d880f1455aea05fe9b47e2da6acf518c0771d300625",
        //        PreviewApiKey = "3aaec008db04a17e144539715f539354ff73cf8d82c2548c3045bbcfc2ee32a2",
        //        SpaceId = "bda2gc49gm0w"
        //    };

        //    var client = new ContentfulClient(httpClient, options);
        //    var PageInfo = await client.GetEntry<Pages>(PageID);
        //    List<string> CurrentPageEntries = new List<string>();
        //    foreach(var item in PageInfo.modules) { CurrentPageEntries.Add(item["sys"]["id"].ToString()); }

        //    return View();
        //}

        public async Task<ActionResult> About()
        {
            HttpClient httpClient = new HttpClient();
            var options = new ContentfulOptions
            {
                DeliveryApiKey = "4df4c5c7ed276605d36b9d880f1455aea05fe9b47e2da6acf518c0771d300625",
                PreviewApiKey = "3aaec008db04a17e144539715f539354ff73cf8d82c2548c3045bbcfc2ee32a2",
                SpaceId = "bda2gc49gm0w"
            };

            var client = new ContentfulClient(httpClient, options);


            var PageInfo = await client.GetEntry<Pages>("67fZc5ATyn7AMbKS7W938A");
            List<PageContent> currentPageContents = new List<PageContent>();

            foreach (var item in PageInfo.modules)
            {
                currentPageContents.Add(await client.GetEntry<PageContent>(item["sys"]["id"].ToString()));
            }

            return View(currentPageContents);
        }

        public async Task<ActionResult> Contact()
        {
            HttpClient httpClient = new HttpClient();
            var options = new ContentfulOptions
            {
                DeliveryApiKey = "4df4c5c7ed276605d36b9d880f1455aea05fe9b47e2da6acf518c0771d300625",
                PreviewApiKey = "3aaec008db04a17e144539715f539354ff73cf8d82c2548c3045bbcfc2ee32a2",
                SpaceId = "bda2gc49gm0w"
            };

            var client = new ContentfulClient(httpClient, options);
            var PageInfo = await client.GetEntry<Pages>("6pe3lPKCzpsyz9nZBpJzbr");
            List<PageContent> currentPageContents = new List<PageContent>();

            foreach (var item in PageInfo.modules)
            {
                currentPageContents.Add(await client.GetEntry<PageContent>(item["sys"]["id"].ToString()));
            }

            return View(currentPageContents);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ 
        System.Globalization.CultureInfo cultureInfo = System.Threading.Thread.CurrentThread.CurrentCulture;
        System.Globalization.TextInfo textInfo = cultureInfo.TextInfo;
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">@(HttpContext.Current.Session["username"] == null ? "Contentful" : "Selamlar , " + textInfo.ToTitleCase(HttpContext.Current.Session["username"].ToString()))</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkımızda", "About", "Pages")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Pages")</li>
                    <li>@Html.ActionLink("Giriş Yap", "Index","State")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>